- hosts: localhost
  remote_user: kubuntu
  vars:
    HOME: /home/kubuntu
  become: yes
  vars:
    virtualenvwrapper_path: "/usr/share/virtualenvwrapper/virtualenvwrapper.sh"
  tasks:
  - name: ensure that git is installed
    apt:
      name: git
      state: latest
  - name: ensure that python3-pip is installed
    apt:
      name: python3-pip
      state: latest
  - name: 
    apt:
      name: virtualenvwrapper
      state: latest
  - name: install ipython
    pip:
      executable: /usr/bin/pip3
      name: ipython
############################# zsh setup #############################
  - name: ensure that zsh is installed
    apt:
      name: zsh
      state: latest
  - name: ensure that fzf is installed
    apt:
      name: fzf
      state: latest
############################# vscodium setup #############################
  - name: add codium gpg
    apt_key:
      url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
  - name: add codium repos
    apt_repository:
      repo: deb https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/ vscodium main
      filename: vscodium
  - name: install codium
    apt:
      name: codium
      update_cache: yes
      state: latest
