- hosts: localhost
  remote_user: kubuntu
  vars:
    ZSH_CUSTOM: "~/.oh-my-zsh/custom"
  tasks:
############################# install all extensions #############################
  - name: install all vscodium extensions
    command: codium --install-extension {{ item }}
    loop:
      - astallinger.sourcetrail
      - coddx.coddx-alpha
      - CoenraadS.bracket-pair-colorizer-2
      - docsmsft.docs-yaml
      - donjayamanne.githistory
      - eamodio.gitlens
      - emmanuelbeziat.vscode-great-icons
      - geddski.macros
      - huizhou.githd
      - ipedrazas.kubernetes-snippets
      - jedmao.tabsanity
      - krvajalm.linter-gfortran
      - mhutchie.git-graph
      - mkloubert.vscode-kanban
      - ms-azuretools.vscode-docker
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - ms-python.python
      - naumovs.color-highlight
      - njpwerner.autodocstring
      - redhat.vscode-yaml
      - s3gf4ult.monokai-vibrant
      - shaharkazaz.git-merger
      - shd101wyy.markdown-preview-enhanced
      - Tyriar.shell-launcher
      - vscoss.vscode-ansible
      - yzhang.markdown-all-in-one
############################# copy ipython config #############################
  - name: create ipython3 default profile
    command: ipython3 profile create default
  - name: create ipython3 custom profiles
    command: ipython3 profile create {{ item }}
    loop:
      - color
      - debug
  - name: copy profiles
    copy:
      src: IPython/profile_{{ item }}/ipython_config.py
      dest: ~/.ipython/profile_{{ item }}/ipython_config.py
    loop:
      - color
      - debug
############################# copy zsh config #############################
  - name: copy custom .zshrc
    copy:
      src: zshrc
      dest: ~/.zshrc
  - name: check if oh-my-zsh directory exists
    stat:
      path: ~/.oh-my-zsh
    register: oh_my_zsh
  - name: ensure that ohmyzsh is installed
    shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    when: oh_my_zsh.stat.exists == false
  - name: ensure that zsh-autosuggestions is installed
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: "{{ ZSH_CUSTOM }}/plugins/zsh-autosuggestions"
  - name: ensure that zsh-syntax-highlighting is installed
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting
      dest: "{{ ZSH_CUSTOM }}/plugins/zsh-syntax-highlighting"
############################# compare_and_merge current files and vscode-setup #############################
  - name: ensure compare_and_merge.sh is executable
    file:
      path: compare_and_merge.sh
      mode: +x
  - name: compare and merge config.json
    shell:
     cmd: "./compare_and_merge.sh ~/.config/VSCodium/User/settings.json settings.json"
  - name: merge keybindings.json
    shell:
     cmd: "./compare_and_merge.sh ~/.config/VSCodium/User/keybindings.json keybindings.json"
