- hosts: localhost
  remote_user: kubuntu
  tasks:
############################# install all extensions #############################
  - name: install all vscodium extensions
    command: codium --install-extension {{ item }}
    loop:
      - astallinger.sourcetrail
      - coddx.coddx-alpha
      - CoenraadS.bracket-pair-colorizer-2
      - docsmsft.docs-yaml
      - donjayamanne.githistory
      - eamodio.gitlens
      - emmanuelbeziat.vscode-great-icons
      - geddski.macros
      - huizhou.githd
      - ipedrazas.kubernetes-snippets
      - jedmao.tabsanity
      - krvajalm.linter-gfortran
      - mhutchie.git-graph
      - mkloubert.vscode-kanban
      - ms-azuretools.vscode-docker
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - ms-python.python
      - naumovs.color-highlight
      - njpwerner.autodocstring
      - redhat.vscode-yaml
      - s3gf4ult.monokai-vibrant
      - shaharkazaz.git-merger
      - shd101wyy.markdown-preview-enhanced
      - Tyriar.shell-launcher
      - vscoss.vscode-ansible
      - yzhang.markdown-all-in-one
############################# copy ipython config #############################
  - name: create ipython3 default profile
    command: ipython3 profile create default
  - name: create ipython3 custom profiles
    command: ipython3 profile create {{ item }}
    loop:
      - color
      - debug
  - name: copy profiles
    copy:
      src: IPython/profile_{{ item }}/ipython_config.py
      dest: ~/.ipython/profile_{{ item }}/ipython_config.py
    loop:
      - color
      - debug
############################# copy zsh config #############################
  - name: copy custom .zshrc
    copy:
      src: zshrc
      dest: ~/.zshrc
  - name: ensure that omyzsh is installed
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
############################# merge actual file and vscodium #############################
# use git merge-file: https://git-scm.com/docs/git-merge-file
############################# install Sourcetrail #############################
# install sourcetrail, copying it to /usr/share/Sourcetrail/ and then
# ln -s /usr/share/Sourcetrail/Sourcetrail /usr/bin/Sourcetrail
